export const AllProducts = [
  {
    id:1,
    brand: "E Scooter",
    name: "Electric Scooter 125cc",
    has_variants: false,
    slug: "electric-scooter-125cc",
    image:
      "https://electro.madrasthemes.com/3x/wp-content/uploads/sites/4/2024/02/eScooter4.webp",
    sold_amount: 120,
    review: 4.5,
    retail_price: 120000,
    discount_price: 20500,
    has_discount: true,
    sale_price: 99500,
  },
  {
    id: 2,
    brand: "E Scooter",
    name: "EcoRide X1",
    has_variants: false,
    slug: "ecoride-x1",
    image:
      "https://electro.madrasthemes.com/3x/wp-content/uploads/sites/4/2024/02/eScooter2.webp",
    sold_amount: 95,
    review: 4.3,
    retail_price: 115000,
    discount_price: 15000,
    has_discount: true,
    sale_price: 100000,
  },
  {
    id: 3,
    brand: "E Scooter",
    name: "VoltMax S Pro",
    has_variants: true,
    slug: "voltmax-s-pro",
    image:
      "https://electro.madrasthemes.com/3x/wp-content/uploads/sites/4/2024/02/eScooter4.webp",
    sold_amount: 80,
    review: 4.7,
    retail_price: 135000,
    discount_price: 20000,
    has_discount: true,
    sale_price: 115000,
  },
  {
    id: 4,
    brand: "E Scooter",
    name: "GreenMotion 150",
    has_variants: false,
    slug: "greenmotion-150",
    image:
      "https://electro.madrasthemes.com/3x/wp-content/uploads/sites/4/2024/02/eScooter2.webp",
    sold_amount: 60,
    review: 4.2,
    retail_price: 110000,
    discount_price: 10000,
    has_discount: true,
    sale_price: 100000,
  },
  {
    id: 5,
    brand: "E Scooter",
    name: "Urban Glide E2",
    has_variants: true,
    slug: "urban-glide-e2",
    image:
      "https://electro.madrasthemes.com/3x/wp-content/uploads/sites/4/2024/02/eScooter4.webp",
    sold_amount: 140,
    review: 4.8,
    retail_price: 145000,
    discount_price: 25000,
    has_discount: true,
    sale_price: 120000,
  },
  {
    id: 6,
    brand: "E Scooter",
    name: "Thunder EV 125",
    has_variants: false,
    slug: "thunder-ev-125",
    image:
      "https://electro.madrasthemes.com/3x/wp-content/uploads/sites/4/2024/02/eScooter4.webp",
    sold_amount: 75,
    review: 4.1,
    retail_price: 118000,
    discount_price: 13000,
    has_discount: true,
    sale_price: 105000,
  },
  {
    id: 7,
    brand: "E Scooter",
    name: "SkyRide Electric",
    has_variants: true,
    slug: "skyride-electric",
    image:
      "https://electro.madrasthemes.com/3x/wp-content/uploads/sites/4/2024/02/eScooter4.webp",
    sold_amount: 88,
    review: 4.4,
    retail_price: 125000,
    discount_price: 15000,
    has_discount: true,
    sale_price: 110000,
  },
  {
    id: 8,
    brand: "E Scooter",
    name: "EcoFlash Z",
    has_variants: false,
    slug: "ecoflash-z",
    image:
      "https://electro.madrasthemes.com/3x/wp-content/uploads/sites/4/2024/02/eScooter4.webp",
    sold_amount: 110,
    review: 4.6,
    retail_price: 130000,
    discount_price: 18000,
    has_discount: true,
    sale_price: 112000,
  },
  {
    id: 9,
    brand: "E Scooter",
    name: "PowerCruise EV",
    has_variants: true,
    slug: "powercruise-ev",
    image:
      "https://electro.madrasthemes.com/3x/wp-content/uploads/sites/4/2024/02/eScooter4.webp",
    sold_amount: 68,
    review: 4.0,
    retail_price: 140000,
    discount_price: 22000,
    has_discount: true,
    sale_price: 118000,
  },
  {
    id: 10,
    brand: "E Scooter",
    name: "SmartRide Neo",
    has_variants: false,
    slug: "smartride-neo",
    image:
      "https://electro.madrasthemes.com/3x/wp-content/uploads/sites/4/2024/02/eScooter4.webp",
    sold_amount: 102,
    review: 4.5,
    retail_price: 122000,
    discount_price: 12000,
    has_discount: true,
    sale_price: 110000,
  },
   {
    id: 11,
    brand: "E Scooter Audio",
    name: "Bass Boost Earbuds X1",
    has_variants: false,
    slug: "bass-boost-earbuds-x1",
    image:
      "https://electro.madrasthemes.com/3x/wp-content/uploads/sites/4/2024/02/EarbudsGreen.webp",
    sold_amount: 120,
    review: 4.5,
    retail_price: 2500,
    discount_price: 500,
    has_discount: true,
    sale_price: 2000,
  },
  {
    id: 12,
    brand: "SoundMax",
    name: "Wireless Earphones Pro",
    has_variants: false,
    slug: "wireless-earphones-pro",
    image:
      "https://electro.madrasthemes.com/3x/wp-content/uploads/sites/4/2024/02/Headphones.webp",
    sold_amount: 95,
    review: 4.3,
    retail_price: 3000,
    discount_price: 800,
    has_discount: true,
    sale_price: 2200,
  },
  {
    id: 13,
    brand: "AudioTech",
    name: "Noise Cancelling Buds",
    has_variants: true,
    slug: "noise-cancelling-buds",
    image:
      "https://electro.madrasthemes.com/3x/wp-content/uploads/sites/4/2024/02/Earphones.webp",
    sold_amount: 80,
    review: 4.7,
    retail_price: 5000,
    discount_price: 1000,
    has_discount: true,
    sale_price: 4000,
  },
  {
    id: 14,
    brand: "BassLine",
    name: "Deep Bass Earbuds",
    has_variants: false,
    slug: "deep-bass-earbuds",
    image:
      "https://images.unsplash.com/photo-1583394838336-acd977736f90",
    sold_amount: 60,
    review: 4.2,
    retail_price: 1800,
    discount_price: 300,
    has_discount: true,
    sale_price: 1500,
  },
  {
    id: 15,
    brand: "ZenSound",
    name: "Comfort Fit Earphones",
    has_variants: false,
    slug: "comfort-fit-earphones",
    image:
      "https://electro.madrasthemes.com/3x/wp-content/uploads/sites/4/2024/02/Earphones.webp",
    sold_amount: 140,
    review: 4.8,
    retail_price: 3500,
    discount_price: 700,
    has_discount: true,
    sale_price: 2800,
  },
  {
    id: 16,
    brand: "NeoAudio",
    name: "Gaming Earbuds Low Latency",
    has_variants: true,
    slug: "gaming-earbuds-low-latency",
    image:
      "https://images.unsplash.com/photo-1583394838336-acd977736f90",
    sold_amount: 75,
    review: 4.1,
    retail_price: 4500,
    discount_price: 900,
    has_discount: true,
    sale_price: 3600,
  },
  {
    id: 17,
    brand: "WaveSound",
    name: "Crystal Clear Audio Buds",
    has_variants: false,
    slug: "crystal-clear-audio-buds",
    image:
      "https://electro.madrasthemes.com/3x/wp-content/uploads/sites/4/2024/02/Earphones.webp",
    sold_amount: 88,
    review: 4.4,
    retail_price: 2700,
    discount_price: 600,
    has_discount: true,
    sale_price: 2100,
  },
  {
    id: 18,
    brand: "EchoTech",
    name: "Smart Touch Earbuds",
    has_variants: false,
    slug: "smart-touch-earbuds",
    image:
      "https://images.unsplash.com/photo-1583394838336-acd977736f90",
    sold_amount: 110,
    review: 4.6,
    retail_price: 3200,
    discount_price: 700,
    has_discount: true,
    sale_price: 2500,
  },
  {
    id: 19,
    brand: "AirBeat",
    name: "Ultra Light Earbuds",
    has_variants: true,
    slug: "ultra-light-earbuds",
    image:
      "https://electro.madrasthemes.com/3x/wp-content/uploads/sites/4/2024/02/Earphones.webp",
    sold_amount: 68,
    review: 4.0,
    retail_price: 2200,
    discount_price: 400,
    has_discount: true,
    sale_price: 1800,
  },
  {
    id: 20,
    brand: "ProSound",
    name: "Studio Quality Earphones",
    has_variants: false,
    slug: "studio-quality-earphones",
    image:
      "https://images.unsplash.com/photo-1583394838336-acd977736f90",
    sold_amount: 102,
    review: 4.5,
    retail_price: 6000,
    discount_price: 1200,
    has_discount: true,
    sale_price: 4800,
  },
   {
    id: 21,
    brand: "E Scooter Audio",
    name: "Bass Boost Earbuds X1",
    has_variants: false,
    slug: "bass-boost-earbuds-x1",
    image:
      "https://electro.madrasthemes.com/3x/wp-content/uploads/sites/4/2024/02/EarbudsGreen.webp",
    sold_amount: 120,
    review: 4.5,
    retail_price: 2500,
    discount_price: 500,
    has_discount: true,
    sale_price: 2000,
  },
  {
    id: 22,
    brand: "AudioTech",
    name: "Noise Cancelling Buds",
    has_variants: true,
    slug: "noise-cancelling-buds",
    image:
      "https://electro.madrasthemes.com/3x/wp-content/uploads/sites/4/2024/02/Earphones.webp",
    sold_amount: 80,
    review: 4.7,
    retail_price: 5000,
    discount_price: 1000,
    sale_price: 4000,
    has_discount: true,
  },
  {
    id: 23,
    brand: "NeoAudio",
    name: "Gaming Earbuds Low Latency",
    has_variants: true,
    slug: "gaming-earbuds-low-latency",
    image:
      "https://www.startech.com.bd/image/cache/catalog/earbuds/defy/gravity-turbo/gravity-turbo-01-500x500.webp",
    sold_amount: 75,
    review: 4.1,
    retail_price: 4500,
    discount_price: 900,
    sale_price: 3600,
    has_discount: true,
  },
  {
    id: 24,
    brand: "AirBeat",
    name: "Ultra Light Earbuds",
    has_variants: true,
    slug: "ultra-light-earbuds",
    image:
      "https://electro.madrasthemes.com/3x/wp-content/uploads/sites/4/2024/02/Earphones.webp",
    sold_amount: 68,
    review: 4.0,
    retail_price: 2200,
    discount_price: 400,
    sale_price: 1800,
    has_discount: true,
  },
  {
    id: 25,
    brand: "Canon",
    name: "EOS R50 Mirrorless Camera",
    has_variants: true,
    slug: "canon-eos-r50",
    image:
      "https://www.startech.com.bd/image/cache/catalog/camera/mirriorless/canon/eos-r50-dual-lens/eos-r50-dual-lens-01-500x500.webp",
    sold_amount: 75,
    review: 4.8,
    retail_price: 98000,
    discount_price: 6000,
    sale_price: 92000,
    has_discount: true,
  },
  {
    id: 26,
    brand: "Apple",
    name: "Apple Watch Series 9",
    has_variants: true,
    slug: "apple-watch-series-9",
    image:
      "https://ddfndelma2gpn.cloudfront.net/color/220/apple_watch_series_9_graphite.webp",
    sold_amount: 190,
    review: 4.7,
    retail_price: 55000,
    discount_price: 5000,
    sale_price: 50000,
    has_discount: true,
  },
  {
    id: 27,
    brand: "JBL",
    name: "Bluetooth Portable Speaker",
    has_variants: false,
    slug: "jbl-portable-speaker",
    image:
      "https://www.penguin.com.bd/wp-content/uploads/2026/04/1720427551000109-1-1-300x300.webp",
    sold_amount: 220,
    review: 4.5,
    retail_price: 18000,
    discount_price: 3000,
    sale_price: 15000,
    has_discount: true,
  },
  {
    id: 28,
    brand: "Logitech",
    name: "Mechanical RGB Gaming Keyboard",
    has_variants: true,
    slug: "logitech-rgb-keyboard",
    image:
      "https://www.ultratech.com.bd/image/cache/catalog/PC-Power/pc-power-k98-rgb-gaming-mechanical-keyboard-white-500x500.jpg",
    sold_amount: 170,
    review: 4.6,
    retail_price: 1200,
    discount_price: 200,
    sale_price: 1000,
    has_discount: true,
  },
  {
    id: 29,
    brand: "Xiaomi",
    name: "Mi Electric Bike Pro",
    has_variants: false,
    slug: "mi-electric-bike-pro",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQe5zyxnFSZd8If2eT4d-TINZy8mrqB7hVTKs5LbmhE9A&s=10",
    sold_amount: 55,
    review: 4.7,
    retail_price: 145000,
    discount_price: 10000,
    sale_price: 135000,
    has_discount: true,
  },
  {
    id: 30,
    brand: "E Scooter",
    name: "Electric Scooter 125cc",
    has_variants: false,
    slug: "electric-scooter-125cc",
    image:
      "https://electro.madrasthemes.com/3x/wp-content/uploads/sites/4/2024/02/eScooter4.webp",
    sold_amount: 120,
    review: 4.5,
    retail_price: 120000,
    discount_price: 20500,
    sale_price: 99500,
    has_discount: true,
  },
  {
    id: 31,
    brand: "DJI",
    name: "Mini 4 Pro Drone",
    has_variants: true,
    slug: "dji-mini-4-pro",
    image:
      "https://diamu.com.bd/wp-content/uploads/2023/09/DJI-Mini-4-Pro-Camera-Drone-4.jpg",
    sold_amount: 95,
    review: 4.9,
    retail_price: 120000,
    discount_price: 10000,
    sale_price: 110000,
    has_discount: true,
  },
  {
    id: 32,
    brand: "Asus",
    name: "ROG Gaming PC RTX 4070",
    has_variants: true,
    slug: "rog-gaming-pc-rtx4070",
    image:
      "https://dlcdnwebimgs.asus.com/gain/7E4B6277-C5F1-4BEE-87E0-548530BA084B/w717/h525",
    sold_amount: 60,
    review: 4.9,
    retail_price: 250000,
    discount_price: 15000,
    sale_price: 235000,
    has_discount: true,
  },
  {
    id: 33,
    brand: "Apple",
    name: "iPhone 15 Pro Max",
    has_variants: true,
    slug: "iphone-15-pro-max",
    image:
      "https://www.outletexpense.xyz/uploads/356-MD.-Din-Islam/1775992205_69db7d8d6d195.jpg",
    sold_amount: 300,
    review: 4.9,
    retail_price: 180000,
    discount_price: 10000,
    sale_price: 170000,
    has_discount: true,
  },
  {
    id: 34,
    brand: "Samsung",
    name: "Galaxy Tab S9 Ultra",
    has_variants: true,
    slug: "galaxy-tab-s9-ultra",
    image:
      "https://www.custommacbd.com/cdn/shop/files/Galaxy-Tab-S9-Ultra-Beige-Custom-Mac-BD.jpg?v=1694153641",
    sold_amount: 85,
    review: 4.7,
    retail_price: 130000,
    discount_price: 8000,
    sale_price: 122000,
    has_discount: true,
  },
  {
    id: 35,
    brand: "LG",
    name: "55 Inch 4K Smart TV",
    has_variants: false,
    slug: "lg-55-4k-smart-tv",
    image:
      "https://shamimelectronics.com.bd/wp-content/uploads/2024/03/860X740-01-14-1.jpeg",
    sold_amount: 140,
    review: 4.6,
    retail_price: 95000,
    discount_price: 7000,
    sale_price: 88000,
    has_discount: true,
  },
  {
    id: 36,
    brand: "Canon",
    name: "EOS R50 Mirrorless Camera",
    has_variants: true,
    slug: "canon-eos-r50",
    image:
      "https://www.startech.com.bd/image/cache/catalog/camera/mirriorless/canon/eos-r50-dual-lens/eos-r50-dual-lens-01-500x500.webp",
    sold_amount: 75,
    review: 4.8,
    retail_price: 98000,
    discount_price: 6000,
    sale_price: 92000,
    has_discount: true,
  },
  {
    id: 37,
    brand: "Apple",
    name: "Apple Watch Series 9",
    has_variants: true,
    slug: "apple-watch-series-9",
    image:
      "https://ddfndelma2gpn.cloudfront.net/color/220/apple_watch_series_9_graphite.webp",
    sold_amount: 190,
    review: 4.7,
    retail_price: 55000,
    discount_price: 5000,
    sale_price: 50000,
    has_discount: true,
  },
  {
    id: 38,
    brand: "JBL",
    name: "Bluetooth Portable Speaker",
    has_variants: false,
    slug: "jbl-portable-speaker",
    image:
      "https://www.penguin.com.bd/wp-content/uploads/2026/04/1720427551000109-1-1-300x300.webp",
    sold_amount: 220,
    review: 4.5,
    retail_price: 18000,
    discount_price: 3000,
    sale_price: 15000,
    has_discount: true,
  },
  {
    id: 39,
    brand: "Logitech",
    name: "Mechanical RGB Gaming Keyboard",
    has_variants: true,
    slug: "logitech-rgb-keyboard",
    image:
      "https://www.ultratech.com.bd/image/cache/catalog/PC-Power/pc-power-k98-rgb-gaming-mechanical-keyboard-white-500x500.jpg",
    sold_amount: 170,
    review: 4.6,
    retail_price: 1200,
    discount_price: 200,
    sale_price: 1000,
    has_discount: true,
  },
  {
    id: 40,
    brand: "E Scooter",
    name: "EcoRide X1",
    has_variants: false,
    slug: "ecoride-x1",
    image:
      "https://electro.madrasthemes.com/3x/wp-content/uploads/sites/4/2024/02/eScooter2.webp",
    sold_amount: 95,
    review: 4.3,
    retail_price: 115000,
    discount_price: 15000,
    sale_price: 100000,
    has_discount: true,
  },
  {
    id: 41,
    brand: "E Scooter",
    name: "VoltMax S Pro",
    has_variants: true,
    slug: "voltmax-s-pro",
    image:
      "https://electro.madrasthemes.com/3x/wp-content/uploads/sites/4/2024/02/eScooter4.webp",
    sold_amount: 80,
    review: 4.7,
    retail_price: 135000,
    discount_price: 20000,
    sale_price: 115000,
    has_discount: true,
  },
  {
    id: 42,
    brand: "E Scooter",
    name: "GreenMotion 150",
    has_variants: false,
    slug: "greenmotion-150",
    image:
      "https://electro.madrasthemes.com/3x/wp-content/uploads/sites/4/2024/02/eScooter2.webp",
    sold_amount: 60,
    review: 4.2,
    retail_price: 110000,
    discount_price: 10000,
    sale_price: 100000,
    has_discount: true,
  },
  {
    id: 43,
    brand: "E Scooter",
    name: "Urban Glide E2",
    has_variants: true,
    slug: "urban-glide-e2",
    image:
      "https://electro.madrasthemes.com/3x/wp-content/uploads/sites/4/2024/02/eScooter4.webp",
    sold_amount: 140,
    review: 4.8,
    retail_price: 145000,
    discount_price: 25000,
    sale_price: 120000,
    has_discount: true,
  },
  {
    id: 44,
    brand: "JBL",
    name: "Bluetooth Portable Speaker",
    has_variants: false,
    slug: "jbl-portable-speaker",
    image:
      "https://www.penguin.com.bd/wp-content/uploads/2026/04/1720427551000109-1-1-300x300.webp",
    sold_amount: 220,
    review: 4.5,
    retail_price: 18000,
    discount_price: 3000,
    sale_price: 15000,
    has_discount: true,
  },
  {
    id: 45,
    brand: "Logitech",
    name: "Mechanical RGB Gaming Keyboard",
    has_variants: true,
    slug: "logitech-rgb-keyboard",
    image:
      "https://www.ultratech.com.bd/image/cache/catalog/PC-Power/pc-power-k98-rgb-gaming-mechanical-keyboard-white-500x500.jpg",
    sold_amount: 170,
    review: 4.6,
    retail_price: 1200,
    discount_price: 200,
    sale_price: 1000,
    has_discount: true,
  },
  {
    id: 46,
    brand: "WaveSound",
    name: "Crystal Clear Audio Buds",
    has_variants: false,
    slug: "crystal-clear-audio-buds",
    image:
      "https://electro.madrasthemes.com/3x/wp-content/uploads/sites/4/2024/02/Earphones.webp",
    sold_amount: 88,
    review: 4.4,
    retail_price: 2700,
    discount_price: 600,
    sale_price: 2100,
    has_discount: true,
  },
  {
    id: 47,
    brand: "EchoTech",
    name: "Smart Touch Earbuds",
    has_variants: false,
    slug: "smart-touch-earbuds",
    image:
      "https://www.startech.com.bd/image/cache/catalog/earbuds/defy/gravity-turbo/gravity-turbo-01-500x500.webp",
    sold_amount: 110,
    review: 4.6,
    retail_price: 3200,
    discount_price: 700,
    sale_price: 2500,
    has_discount: true,
  },
  {
    id: 48,
    brand: "E Scooter Audio",
    name: "Bass Boost Earbuds X1",
    has_variants: false,
    slug: "bass-boost-earbuds-x1",
    image:
      "https://electro.madrasthemes.com/3x/wp-content/uploads/sites/4/2024/02/EarbudsGreen.webp",
    sold_amount: 120,
    review: 4.5,
    retail_price: 2500,
    discount_price: 500,
    sale_price: 2000,
    has_discount: true,
  },
  {
    id: 49,
    brand: "AudioTech",
    name: "Noise Cancelling Buds",
    has_variants: true,
    slug: "noise-cancelling-buds",
    image:
      "https://electro.madrasthemes.com/3x/wp-content/uploads/sites/4/2024/02/Earphones.webp",
    sold_amount: 80,
    review: 4.7,
    retail_price: 5000,
    discount_price: 1000,
    sale_price: 4000,
    has_discount: true,
  },
  {
    id: 50,
    brand: "NeoAudio",
    name: "Gaming Earbuds Low Latency",
    has_variants: true,
    slug: "gaming-earbuds-low-latency",
    image:
      "https://www.startech.com.bd/image/cache/catalog/earbuds/defy/gravity-turbo/gravity-turbo-01-500x500.webp",
    sold_amount: 75,
    review: 4.1,
    retail_price: 4500,
    discount_price: 900,
    sale_price: 3600,
    has_discount: true,
  },
   {
    id: 51,
    brand: "E Scooter",
    name: "Electric Scooter 125cc",
    has_variants: false,
    slug: "electric-scooter-125cc",
    image:
      "https://electro.madrasthemes.com/3x/wp-content/uploads/sites/4/2024/02/eScooter4.webp",
    sold_amount: 120,
    review: 4.5,
    retail_price: 120000,
    discount_price: 20500,
    sale_price: 99500,
    has_discount: true,
  },
  {
    id: 52,
    brand: "Sony",
    name: "WH-1000XM5 Wireless Headphones",
    has_variants: true,
    slug: "sony-wh1000xm5",
    image:
      "https://ecom.rangs.com.bd/storage/10981/860X740-01.jpg",
    sold_amount: 240,
    review: 4.8,
    retail_price: 45000,
    discount_price: 5000,
    sale_price: 40000,
    has_discount: true,
  },
  {
    id: 53,
    brand: "DJI",
    name: "Mini 4 Pro Drone",
    has_variants: true,
    slug: "dji-mini-4-pro",
    image:
      "https://diamu.com.bd/wp-content/uploads/2023/09/DJI-Mini-4-Pro-Camera-Drone-4.jpg",
    sold_amount: 95,
    review: 4.9,
    retail_price: 120000,
    discount_price: 10000,
    sale_price: 110000,
    has_discount: true,
  },
  {
    id: 54,
    brand: "Asus",
    name: "ROG Gaming PC RTX 4070",
    has_variants: true,
    slug: "rog-gaming-pc-rtx4070",
    image:
      "https://dlcdnwebimgs.asus.com/gain/7E4B6277-C5F1-4BEE-87E0-548530BA084B/w717/h525",
    sold_amount: 60,
    review: 4.9,
    retail_price: 250000,
    discount_price: 15000,
    sale_price: 235000,
    has_discount: true,
  },
  {
    id: 55,
    brand: "Apple",
    name: "iPhone 15 Pro Max",
    has_variants: true,
    slug: "iphone-15-pro-max",
    image:
      "https://www.outletexpense.xyz/uploads/356-MD.-Din-Islam/1775992205_69db7d8d6d195.jpg",
    sold_amount: 300,
    review: 4.9,
    retail_price: 180000,
    discount_price: 10000,
    sale_price: 170000,
    has_discount: true,
  },
  {
    id: 56,
    brand: "Samsung",
    name: "Galaxy Tab S9 Ultra",
    has_variants: true,
    slug: "galaxy-tab-s9-ultra",
    image:
      "https://www.custommacbd.com/cdn/shop/files/Galaxy-Tab-S9-Ultra-Beige-Custom-Mac-BD.jpg?v=1694153641",
    sold_amount: 85,
    review: 4.7,
    retail_price: 130000,
    discount_price: 8000,
    sale_price: 122000,
    has_discount: true,
  },
  {
    id: 57,
    brand: "LG",
    name: "55 Inch 4K Smart TV",
    has_variants: false,
    slug: "lg-55-4k-smart-tv",
    image:
      "https://shamimelectronics.com.bd/wp-content/uploads/2024/03/860X740-01-14-1.jpeg",
    sold_amount: 140,
    review: 4.6,
    retail_price: 95000,
    discount_price: 7000,
    sale_price: 88000,
    has_discount: true,
  },
  {
    id: 58,
    brand: "Canon",
    name: "EOS R50 Mirrorless Camera",
    has_variants: true,
    slug: "canon-eos-r50",
    image:
      "https://www.startech.com.bd/image/cache/catalog/camera/mirriorless/canon/eos-r50-dual-lens/eos-r50-dual-lens-01-500x500.webp",
    sold_amount: 75,
    review: 4.8,
    retail_price: 98000,
    discount_price: 6000,
    sale_price: 92000,
    has_discount: true,
  },
  {
    id: 59,
    brand: "Apple",
    name: "Apple Watch Series 9",
    has_variants: true,
    slug: "apple-watch-series-9",
    image:
      "https://ddfndelma2gpn.cloudfront.net/color/220/apple_watch_series_9_graphite.webp",
    sold_amount: 190,
    review: 4.7,
    retail_price: 55000,
    discount_price: 5000,
    sale_price: 50000,
    has_discount: true,
  },
  {
    id: 60,
    brand: "JBL",
    name: "Bluetooth Portable Speaker",
    has_variants: false,
    slug: "jbl-portable-speaker",
    image:
      "https://www.penguin.com.bd/wp-content/uploads/2026/04/1720427551000109-1-1-300x300.webp",
    sold_amount: 220,
    review: 4.5,
    retail_price: 18000,
    discount_price: 3000,
    sale_price: 15000,
    has_discount: true,
  },
  {
    id: 61,
    brand: "Logitech",
    name: "Mechanical RGB Gaming Keyboard",
    has_variants: true,
    slug: "logitech-rgb-keyboard",
    image:
      "https://www.ultratech.com.bd/image/cache/catalog/PC-Power/pc-power-k98-rgb-gaming-mechanical-keyboard-white-500x500.jpg",
    sold_amount: 170,
    review: 4.6,
    retail_price: 1200,
    discount_price: 200,
    sale_price: 1000,
    has_discount: true,
  },
  {
    id: 62,
    brand: "Xiaomi",
    name: "Mi Electric Bike Pro",
    has_variants: false,
    slug: "mi-electric-bike-pro",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQe5zyxnFSZd8If2eT4d-TINZy8mrqB7hVTKs5LbmhE9A&s=10",
    sold_amount: 55,
    review: 4.7,
    retail_price: 145000,
    discount_price: 10000,
    sale_price: 135000,
    has_discount: true,
  },

];